# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

export PATH=/usr/local/bin:$HOME/bin:$PATH
export TERM=xterm-256color
export EDITOR='gvim -f'
export DIFFPROG="gvim -df +0 -s `echo ~/.vim/diftop.vim`"
#export DIFFPROG='xxdiff'
export CCACHE='/usr/local/bin/ccache'
export PROJECT_PATH=~/project
export JPKG_AUTO_UPDATE_RND_TOOLS=1

if [ -f ~/.bashrc_typos_aliases_and_functions ]; then
  source ~/.bashrc_typos_aliases_and_functions
fi

if [ -f ~/.bashrc_colors_and_ps1 ]; then
  source ~/.bashrc_colors_and_ps1
fi

# Put secret configuration settings in ~/.secrets
if [ -f ~/.secrets ]; then
  source ~/.secrets
fi

if [ -f ~/.git-completion.bash ]; then
  . ~/.git-completion.bash
fi

if [ -f ~/.bashrc_lua ]; then
  source ~/.bashrc_lua
fi

# This is the bash_completion location on Mac
if [ -f $(brew --prefix)/etc/bash_completion ]; then
  . $(brew --prefix)/etc/bash_completion
fi

# This is the bash_completion location on Linux
if [ -f /etc/bash_completion ]; then
	. /etc/bash_completion
fi  

# RVM
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting

### Added by the Heroku Toolbelt
export PATH="$PATH:/usr/local/heroku/bin"


